### PR TITLE
Added support for ActiveRecord serialize/deserialize using GlobalID for Sidekiq::Cron::Job arguments.

### PR DESCRIPTION
**Pull request by nyuta01**
Added support for ActiveRecord serialize/deserialize using GlobalID for Sidekiq::Cron::Job arguments.
https://guides.rubyonrails.org/active_job_basics.html#globalid

# Demo
e.g. Use Person model as a arguments of Sidekiq::Cron::Job

```rb
class Person < ApplicationRecord
end

class ExampleJob < ActiveJob::Base
  queue_as :default

  def perform(person)
        puts "person: #{person}, class: #{person.class}"
  end
end


person = Person.create(id: 1)
Sidekiq::Cron::Job.create(name: 'Example', cron: '*/1 * * * *', class: 'ExampleJob', args: person)
```

## Before

```rb
irb(main):043:0> Sidekiq::Cron::Job.find(name: "Example")
=>
#<Sidekiq::Cron::Job:0x00007f5f22e7a580
 @active_job=false,
 @active_job_queue_name_delimiter="",
 @active_job_queue_name_prefix="",
 @args=["#<Person:0x00007f5f22f35ba0>"],
 @cron="*/1 * * * *",
 @date_as_argument=false,
 @description="",
 @errors=[],
 @fetch_missing_args=true,
 @klass="ExampleJob",
 @last_enqueue_time=nil,
 @message="{\"retry\":0,\"queue\":\"default\",\"class\":\"ExampleJob\",\"args\":[\"#<Person:0x00007f5f22f35ba0>\"]}",
 @name="Example",
 @parsed_cron=#<Fugit::Cron:0x00007f5f22e85c78 @cron_s=nil, @day_and=nil, @hours=nil, @minutes=[0, 15, 30, 45], @monthdays=nil, @months=nil, @original="*/1 * * * *", @seconds=[0], @timezone=nil, @weekdays=nil, @zone=nil>,
 @queue="default",
 @queue_name_with_prefix="default",
 @status="enabled",
 @symbolize_args=false>
```

Sidekiq logs

```
[app] I, [2023-02-09T02:17:19.685994 #7]  INFO -- : start
[app] I, [2023-02-09T02:17:19.715124 #7]  INFO -- : Performing ExampleJob (Job ID: cb6eaeb2-a14e-4dc1-8a63-f20c598f60bf) from Sidekiq(default) enqueued at 2023-02-09T02:17:19Z with arguments: "#<Person:0x00007f5f22f35ba0>"
[app] person: #<Person:0x00007f5f22f35ba0>, class: String
...
```

## After

```rb
irb(main):043:0> Sidekiq::Cron::Job.find(name: "Example")
[#<Sidekiq::Cron::Job:0x00007fa3f1487ed8
  @active_job=false,
  @active_job_queue_name_delimiter="",
  @active_job_queue_name_prefix="",
  @args=[{"_sc_globalid"=>"gid://app/Person/1"}],
  @cron="*/1 * * * *",
  @date_as_argument=false,
  @description="",
  @fetch_missing_args=false,
  @klass="ExampleJob",
  @last_enqueue_time=nil,
  @message="{\"retry\":0,\"queue\":\"default\",\"class\":\"ExampleJob\",\"args\":[{\"_sc_globalid\":\"gid://app/Person/1\"}]}",
  @name="Example",
  @queue="default",
  @queue_name_with_prefix="default",
  @status="enabled",
  @symbolize_args=false>]
```

Sidekiq logs

```
[app] I, [2023-02-09T02:40:26.628976 #8]  INFO -- : start
[app] I, [2023-02-09T02:40:27.407155 #8]  INFO -- : Performing ExampleJob (Job ID: d6f6ab18-5790-4afb-9c26-b2be8bd998ca) from Sidekiq(default) enqueued at 2023-02-09T02:40:26Z with arguments: #<GlobalID:0x00007fa29842b318 @uri=#<URI::GID gid://app/Person/1>>
[app] person: #<Person:0x00007fa29845bcc0>, class: Person
```

# References
- https://github.com/rails/rails/blob/v7.0.4/activejob/lib/active_job/arguments.rb

### CODE REVIEW

**Comment by markets** [comment]
Nice feature @nyuta01 👌 

We probably should mention it somewhere in the docs.

**Comment by nyuta01** [comment]
@markets 
Thank you for the review!
If I were to add docs, I would probably make changes to the README, is this something I should do? Or should I request a more knowledgeable contributor to do this?

**Comment by markets** [comment]
Documentation improvements are also really welcome! Feel free to propose changes! 

But in order to avoid this pull request to grow so much, I'd probably just add some mention for now and send improvements in new branches.

**Comment by markets** [comment]
@nyuta01 could you please rebase from master? We added automatic CI runs for different Sidekiq versions.

**Comment by markets** [comment]
Just a couple of minor comments:
- We need some mention in the docs
- We should remove this file (`sidekiq-cron-1.9.1.gem`): https://github.com/sidekiq-cron/sidekiq-cron/pull/395/files#diff-51441cd7981cd2ab547716137b96e19a9b0b56c6eb837fb667fc8202fab28250

**Comment by nyuta01** [comment]
@markets 
Thank you for your comment.
I didn't notice the notification and was late in responding.

I have corrected the areas you pointed out, so please re-review.

**Comment by markets** [comment]
Thank you so much @nyuta01! Merging 🚀

**Review by markets — APPROVED** [review]

**Pull request merged**
