### PR TITLE
Prepare release v2.0.0.rc1

### PR DESCRIPTION
**Pull request by markets**
Full diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.12.0...master

@ondrejbartas @honzasterba Do you agree with this release? Since [`namespaces`](https://github.com/sidekiq-cron/sidekiq-cron#namespacing) is a quite big feature (although retro-compatible with v1), I think it's good timing to start a new major. My idea is to launch it first as a release candidate and then, in some weeks, make the official v2 release.

### CODE REVIEW

**Comment by honzasterba** [comment]
I think versioning should be consistent with
major - breaking change
minor - new feature
patch - bugix
since this is a non breaking change a major release is not necessary, people not following the changelong may be scared to upgrade to major expecting extra work, my vote is to just bump minor

**Comment by markets** [comment]
@honzasterba I agree, consistency with SemVer when releasing libs is something good. I just feel that this release is a little different compared to others, as we introduced significant changes and a couple of major features, so would like to mark as a major bump. 

I think I'm gonna wait some time and convert this to a draft for now, as it seems we have another changes in the cooking: #463. 

Also, I'd like to review (and probably refactor) the current configuration system. As we have a couple of modules (`Sidekiq::Options`vs `Sidekiq::Cron.configure`) that are not 100% clear how they need to be used.

Thanks for the feedback!

**Comment by zedtux** [comment]
Hey @markets 👋,

#463 is now closed. Any news regarding that configuration system refactoring?

Can you remove the draft mode on this PR?

**Comment by ignaciovillaverde** [comment]
Hi @markets, would it make sense to reconsider this PR? Would love to use https://github.com/sidekiq-cron/sidekiq-cron/pull/465 without pointing to the repo's master branch.

**Review by honzasterba — APPROVED** [review]

**Comment by markets** [comment]
Ok! I'll prepare and release this new version during this week.

I'll work on the "config refactor" in the future. Hopefully before the final v2 🙏. Another issue that I'd like to include before the final one: #468, so please, feel free to send a patch, it will be much appreciated 🙂

**Comment by markets** [comment]
v2.0.0.rc1 pushed to RubyGems!

https://rubygems.org/gems/sidekiq-cron/versions/2.0.0.rc1

**Comment by ignaciovillaverde** [comment]
Thank you @markets!

**Pull request merged**
