### PR TITLE
Clarify in readme where to call create

### PR DESCRIPTION
**Pull request by collimarco**
You must call Sidekiq::Cron::Job.create in a file different from the cron job.

### CODE REVIEW

**Comment by ondrejbartas** [comment]
@collimarco I will get executed when you are running in production. But best place to put create is in `cofing/initializers/...`

**Comment by collimarco** [comment]
Keep open

**Comment by markets** [comment]
So what's missing here @ondrejbartas @collimarco? I've never used this approach when using `sidekiq-cron` so I have no strong opinion about this one 🙏🏼 

@ondrejbartas proposed here https://github.com/ondrejbartas/sidekiq-cron/pull/252#issuecomment-608428282 to recommend people to put them under an initializer.

**Comment by honzasterba** [comment]
I don't like the approach because it is specific to Rails. What about adding a Troubleshooting section to the readme. Or just another section around [here](https://github.com/ondrejbartas/sidekiq-cron#forking-processes-or-problem-with-notimplementederror).

**Comment by markets** [comment]
Hello @collimarco 👋🏼 

I agree with @honzasterba, this is too much Rails specific... I propose to create a new section, called "Troubleshooting" and add there the current note about [forking processes](https://github.com/ondrejbartas/sidekiq-cron#forking-processes-or-problem-with-notimplementederror) and this new one about Rails lazy load.

**Comment by collimarco** [comment]
Keep open

**Pull request closed without merging**
