### PR TITLE
Feature: Pagination Feature for Cron Jobs

### PR DESCRIPTION
**Pull request by satyakampandya**
# Pagination Feature for Cron Jobs

This PR updates the Redis commands used in the application to manage cron jobs from SADD (set add) to ZADD (sorted set add). The primary purpose of this change is to leverage the ordering capabilities of Redis sorted sets, which allows for better control over the data order and facilitates easier pagination.

## Data Structure Update:
- Changed from using Redis sets (SADD) to sorted sets (ZADD) to store cron jobs.
- Each cron job is now stored with an associated score that represents its creation time, which allows for sorted retrieval.

## Modification of Adding Members:
- The command SADD jobs_key member is replaced with ZADD jobs_key score member.
- Example change:
```ruby
# Old code using SADD
conn.sadd self.class.jobs_key(@namespace), [redis_key]

# New code using ZADD with time as the score
time = Time.utc.now
conn.zadd self.class.jobs_key(@namespace), time.to_f.to_s, [redis_key]
```

## Pagination Implementation:
- Previously, pagination might have been manually handled or based on unordered sets.
- With ZADD, we can now efficiently paginate results using the scores in the sorted set.
- Example retrieval change:
```ruby
# Old code using SMEMBERS
conn.smembers(jobs_key(namespace))

# New code using ZRANGE with score-based pagination
conn.zrange(jobs_key(namespace), start, stop)
```

## Test Cases Updated:
- Updated unit tests to reflect the change from sets to sorted sets.
- Added new test cases to validate the ordering and pagination of cron jobs.

## Benefits of This Change
- **Improved Data Ordering:** Using ZADD allows us to store data in a sorted order, which is beneficial for retrieving data in a specific sequence without additional sorting logic.
- **Efficient Pagination:** The ordered nature of sorted sets enables straightforward pagination using Redis commands like ZRANGE and ZREVRANGE.
- **Performance Improvements:** By leveraging Redis’s native sorted set operations, we reduce the complexity and potentially increase the performance of data retrieval operations.

## Related Issues
- Feature Request: #474 

## Note
This is my first PR to an open-source project, and I’m excited to contribute! I welcome any feedback or suggestions for improvement. If there are better approaches or practices I could follow, I’m eager to learn and make the necessary adjustments. Thank you for your support and guidance!

### CODE REVIEW

**Comment by satyakampandya** [comment]
### Note on Pagination with * Namespace
Currently, pagination is not supported when the namespace is set to * due to the complexity of managing pagination across multiple namespaces within a loop. One possible solution could be to add an entirely new sorted set that combines all namespaces, which would simplify the pagination logic. However, I'm unsure if this approach is ideal or if it aligns with the overall design principles of the project.

I've added a TODO comment in the code regarding this limitation. If anyone has thoughts on this approach or other suggestions for implementing pagination in this scenario, please share your ideas. I’m open to feedback and improvements!

**Comment by markets** [comment]
Hi @satyakampandya 👋🏼 

First of all, thank you so much for such detailed explanations in this very well formatted PR 👏🏼. Good job!

About the feature: I'm not against adding something like this in the gem, but the code changes seems a bit sensible? I'm not currently very familiar with the Redis internals, so not sure how these changes will impact people updating to this eventual future release. Maintaining complex open-source libraries in the long term is hard, so every time we add a new feature, we are adding more maintenance for the future. 

To be honest, I personally don't need this feature and don't want to maintain more complexity in this library sorry 🙏🏼 ... but if a lot of people wants this, I'm also ok, but I'd like more people to perform code review, give feedback and testing in their apps.

P.S. For the * Namespace thing, I think it will be ok to just raise an exception with something like "You should set a namespace to use the pagination".

**Comment by markets** [comment]
Hello @satyakampandya and thank you again for all the detailed comments 👍🏼

I'm personally not interested in this feature and to deal with more complexity (plus the migration script). The next release, which will be `v2.0.0`, will include another big change: https://github.com/sidekiq-cron/sidekiq-cron/pull/268. I think that performing 2 data migrations during an upgrade is probably too much and potentially bad things can happen (you know, some times shit happens). So, sorry 🙏🏼 but I'm personally not interested in merging and maintaining this feature, at least for now... but if other maintainers want to take the responsibility, that's fine for me too.

**Comment by satyakampandya** [comment]
@markets I completely understand your concerns about handling multiple data migrations in the upcoming release. I appreciate the consideration and respect your decision. If there are any other maintainers who might be interested in taking this forward, I’d be happy to discuss it with them.

Additionally, if there are other features or issues where you need help, I’d be more than happy to contribute.

**Comment by markets** [comment]
Thank you so much for offering your help @satyakampandya! Really appreciated 👌🏼 

If you would like to help with this one #468, I would love to merge it asap.

**Comment by satyakampandya** [comment]
Hello @markets 
Sure, I'll have a look at it.

**Comment by freemanoid** [comment]
I like this feature overall. It should make the UI cleaner. I have a couple of ideas:

1. Pagination without a way to find a particular schedule by name complicates any interaction with the UI. So having a search form that would filter schedules by name would be helpful.
2. I don't think it's a good idea to change redis data structure just for the web UI pagination. We're not talking about tens of thousands of schedules here. A simpler solution would be to avoid changing the data structure and just use `#smembers` and sort the results in ruby. Also, it should be fine to pass an entire array of schedules to the frontend, so the search can be implemented on the frontend without making any additional queries to the backend.

**Comment by satyakampandya** [comment]
@markets, I’ve reverted the sorted sets implementation and switched to using the [SORT](https://redis.io/docs/latest/commands/sort/) method as follows:
```ruby
conn.sort(jobs_key(namespace), 'LIMIT', offset, limit, 'ALPHA')
```
This change works successfully on my local setup and passes all the tests. However, in the CI tests for this PR, I’m encountering the following error:
```
ArgumentError: wrong number of arguments (given 5, expected 1)
    vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/commands/keys.rb:407:in `sort'
```
According to the method definition [here](https://github.com/redis/redis-rb/blob/v4.8.1/lib/redis/commands/keys.rb#L407), it should be used like this:
```ruby
conn.sort(jobs_key(namespace), order: "alpha", limit: [offset, limit])
```
This approach doesn’t work locally. Do you have any insights on this?

**Comment by freemanoid** [comment]
> This approach doesn’t work locally. Do you have any insights on this?

Specs are failing on sidekiq 6. Sidekiq 7 has moved to a different redis client, that is probably the root cause.

**Comment by satyakampandya** [comment]
Thank you @freemanoid for pointing out the issue. 

@markets @freemanoid In this implementation, we preserve the existing Redis data structure without adding any complexity. The changes are simple, utilizing the SORT method rather than altering data structures, which should make ongoing maintenance easier.

If you’re open to reconsidering this PR for the upcoming release, I believe it will improve the UI experience for users while keeping the Redis structure intact.

**Comment by freemanoid** [comment]
> If you’re open to reconsidering this PR for the upcoming release, I believe it will improve the UI experience for users while keeping the Redis structure intact.

IMO adding pagination without a way to filter jobs by name is worse than what we have currently. I never go to the cron UI to "browse" the jobs. I need to find a particular job by a substring. Currently, I search on a page using a browser search.

**Comment by kevinrobell-st** [comment]
How does this new pagination approach handle disabled schedules? Currently disabled cron schedules are shown in a block at the bottom of the cron page in the Sidekiq web UI.

**Comment by markets** [comment]
The new approach, without changing the data structures, is much more feasible to be eventually merged. But I'm still a bit doubtful about this feature in general. Good points raised above by @freemanoid @kevinrobell-st.

**Comment by satyakampandya** [comment]
> IMO adding pagination without a way to filter jobs by name is worse than what we have currently. I never go to the cron UI to "browse" the jobs. I need to find a particular job by a substring. Currently, I search on a page using a browser search.
@freemanoid, I understand your concern about filtering jobs by name, but I believe pagination is still valuable, especially since we already have a namespace filter.

> How does this new pagination approach handle disabled schedules? Currently disabled cron schedules are shown in a block at the bottom of the cron page in the Sidekiq web UI.
@kevinrobell-st, instead of moving disabled cron schedules to the bottom, we can update the UI to display them in their default positions while clearly marking them as disabled. This approach maintains the overall order and visibility.

**Comment by kevinrobell-st** [comment]
I think that approach will make it harder to find any individual job or group of disabled jobs. Having to potentially click through all of the pages to find a job seems like a frustrating user experience.

**Comment by markets** [comment]
I agree with @kevinrobell-st... I think we will need too much changes in the code and extra complexity to support pagination in the admin panel (with no clear benefits between current solution). 

The current solution with namespaces can help to group jobs and you can also use the browser native search if you're looking for a specific job. At the end of the day, this is just like an internal page for developers... It's not worth it. I'd just close it.

**Comment by satyakampandya** [comment]
At this point, I don't see an optimal solution for implementing the search functionality, so I suggest we go ahead and close this PR for now.

**Pull request closed without merging**
