### PR TITLE
Destroy all scheduled jobs before load a new on startup

### PR DESCRIPTION
**Pull request by dapi**
The problem: Sidekiq::Cron continue to store tasks that are no longer in the default config (config/schedule.yml
)
Solution: Destry all old jobs from cron before load new.

### CODE REVIEW

**Comment by markets** [comment]
Hello @dapi 👋🏼

That makes sense to me! Let me ask @sandip-mane and @machisuke as they were both implied in the implementation of this feature.

**Comment by sandip-mane** [comment]
@markets I had this doubt in the main PR itself. Ref: https://github.com/sidekiq-cron/sidekiq-cron/pull/337#issuecomment-1160347813

I guess using just the bang versions of these methods should fix the issue.

https://github.com/sidekiq-cron/sidekiq-cron/blob/71c02bfbe91ee1c22acb768b5fc0de4c280357dc/lib/sidekiq/cron/schedule_loader.rb#L12-L18

**Comment by markets** [comment]
> I guess using just the bang versions of these methods should fix the issue.

Oh yes! You're right @sandip-mane! Thanks for your review!

**Comment by markets** [comment]
@dapi could you please update the patch? The bang! versions should do the job.

**Comment by markets** [comment]
hey @dapi 👋🏼 Did you have the chance to review those comments? I'd like to include this patch in the next release.

**Comment by sandip-mane** [comment]
I can update the PR if it's urgent. When is the release planned for?

**Comment by markets** [comment]
Thanks @sandip-mane! We still don't have a date planned for the release, but we started to work on it.

**Comment by sandip-mane** [comment]
@markets I've raised a new PR #405 as I was not able to update this.

**Comment by markets** [comment]
Fixed in https://github.com/sidekiq-cron/sidekiq-cron/commit/48c2563a77fb9dac4ef4e881bf934ae67f1f42ab

**Comment by zaratan** [comment]
Hey ! I know this is a old issue but would that be ok for you if it was possible to remove this with a configuration flag or env variable ? We manage our cron-scheduled jobs both in the schedule.yml and through code and every reboot/redeploy our code managed cron-scheduled jobs are removed. I pinned the version of sidekiq-cron to `1.9.1` because of this.

**Comment by zaratan** [comment]
I don't mind making the PR for this.

**Comment by markets** [comment]
Hello @zaratan 👋🏼  

If you want to avoid the auto-reload of the schedule, you can just use a different YAML file name:

https://github.com/sidekiq-cron/sidekiq-cron/blob/aacd84bd08032b63917bb354e8b9607386388807/lib/sidekiq/cron/schedule_loader.rb#L9

This will avoid to enter that `if` code path and call the `Sidekiq::Cron::Job.load_from_hash!`. 

See more in the original PR: https://github.com/sidekiq-cron/sidekiq-cron/pull/337

**Comment by zaratan** [comment]
Using a different YAML filename and loading manualy with `load_from_hash` should work indeed. Thanks !

**Pull request closed without merging**
